set(APPLICATION_DESCRIPTION "NM PBX Desktop Client")
set(APPLICATION_ID "uk.co.netmatters.nmpbx")
set(APPLICATION_NAME "NM PBX")
set(APPLICATION_URL "https://www.netmatters.co.uk/")
set(APPLICATION_VENDOR "Netmatters")
set(APPLICATION_LICENCE "GNU General Public License V3")
set(APPLICATION_LICENCE_URL "https://www.gnu.org/licenses/gpl-3.0.html")
set(APPLICATION_START_LICENCE "2025")
set(APPLICATION_SEMVER ${LINPHONEAPP_VERSION})
set(EXECUTABLE_NAME nm-pbx)